version: "3.3"
services:
    
    web:
        build:
            dockerfile: microservices/dockerfiles/DockerfileUrlShortener
            context: ./
        environment:
            - ENVIRONMENT_OVERRIDE=docker
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
          # HOST:CONTAINER
            - 5020:5000
            
    kgs:
        build:
            dockerfile: microservices/dockerfiles/DockerfileKeyGeneratorService
            context: ./
        environment:
            - ENVIRONMENT_OVERRIDE=docker
            - ASPNETCORE_ENVIRONMENT=Development
        ports:
          # HOST:CONTAINER
            - 5021:5000
            
