version: "3.3"
services:
    
    keydb:
        container_name: keydb
        image: mongo
        restart: unless-stopped
        env_file: 
            - env/keydb.env
        volumes:
            - ./init/keydb-init.js:/docker-entrypoint-initdb.d/keydb-init.js:ro
        ports:
            - 27017:27017

    mongo-express-keydb:
        container_name: mongo-express-keydb
        image: mongo-express
        restart: always
        env_file: 
            - env/me_keydb.env
        ports:
            - 8081:8081            
        depends_on:
            - keydb
            
    urldb:
        container_name: urldb
        image: mongo
        restart: always
        env_file: 
            - env/urldb.env
        volumes:
            - ./init/urldb-init.js:/docker-entrypoint-initdb.d/urldb-init.js:ro
        ports:
            - 27018:27017

    mongo-express-urldb:
        container_name: mongo-express-urldb
        image: mongo-express
        restart: always
        env_file: 
            - env/me_urldb.env
        ports:
            - 8082:8081
            
        depends_on:
            - urldb
    
    web:
        build:
            dockerfile: microservices/dockerfiles/DockerfileUrlShortener
            context: ./
        environment:
            - ENVIRONMENT_OVERRIDE=docker
            - ASPNETCORE_ENVIRONMENT=docker
        ports:
            # HOST:CONTAINER
            - 5020:5000
        depends_on:
            - keydb
            - urldb
            
    kgs:
        build:
            dockerfile: microservices/dockerfiles/DockerfileKeyGeneratorService
            context: ./
        environment:
            - ENVIRONMENT_OVERRIDE=docker
            - ASPNETCORE_ENVIRONMENT=docker
        ports:
          # HOST:CONTAINER
            - 5021:5000
        depends_on:
            - keydb
            
    frontend:
        build:
            dockerfile: microservices/dockerfiles/DockerfileFrontend
            context: ./
        ports:
            - "8080:8080"
        container_name: frontend
        volumes:
            - ./frontend:/usr/src/app/frontend
            - /usr/src/app/frontend/node_modules