version: "3.3"
services:
    
    keydb:
        container_name: keydb
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        # volumes:
            # - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
            - 27017:27017

    mongo-express-keydb:
        container_name: mongo-express-keydb
        image: mongo-express
        restart: always
        ports:
            - 8081:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_SERVER: keydb
            ME_CONFIG_MONGODB_PORT: 27017
            # ME_CONFIG_MONGODB_URL: mongodb://root:example@localhost:27017/
            
        depends_on:
            - keydb
            
    urldb:
        container_name: urldb
        image: mongo
        restart: always
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: example
        # volumes:
            # - ${WEBAPP_STORAGE_HOME}/site:/data/db
        ports:
            - 27018:27017

    mongo-express-urldb:
        container_name: mongo-express-urldb
        image: mongo-express
        restart: always
        ports:
            - 8082:8081
        environment:
            ME_CONFIG_MONGODB_ADMINUSERNAME: root
            ME_CONFIG_MONGODB_ADMINPASSWORD: example
            ME_CONFIG_MONGODB_SERVER: urldb
            ME_CONFIG_MONGODB_PORT: 27017
            # ME_CONFIG_MONGODB_URL: mongodb://root:example@localhost:27017/
            
        depends_on:
            - urldb
    
            